
export const CELEBRATION_TEXT_MAP: Record<string, string> = {
  '3d-small': 'NICE!',
  '3d-decent': 'SOLID\nGAIN!',
  '3d-big': 'BIG\nWIN!',
  '3d-huge': 'HUGE\nSCORE!',
  '3d-legendary': 'LEGENDARY!',
  '3d-epic': 'EPIC\nWIN!',
  '3d-mythical': 'MYTHICAL!',
  '3d-godlike': 'GODLIKE!',
  '3d-transcendent': 'TRANSCENDENT!',
  '3d-ouch': 'OUCH!',
  '3d-bruised': 'BRUISED!',
  '3d-wounded': 'WOUNDED!',
  '3d-bleeding': 'BLEEDING!',
  '3d-crushed': 'CRUSHED!',
  '3d-shattered': 'SHATTERED!',
  '3d-obliterated': 'OBLITERATED!',
  '3d-annihilated': 'ANNIHILATED!',
  '3d-vaporized': 'VAPORIZED!',
  '3d-rug-burning': 'RUG\nPULLED!',
  '3d-fire': 'ON\nFIRE!',
  '3d-mega': 'MEGA\nWIN!',
  '3d-win': 'BIG\nWIN!',
};


export const CELEBRATION_TEXT_LINES_MAP: Record<string, string[]> = {
  '3d-small': ['NICE!'],
  '3d-decent': ['SOLID', 'GAIN!'],
  '3d-big': ['BIG', 'WIN!'],
  '3d-huge': ['HUGE', 'SCORE!'],
  '3d-legendary': ['LEGENDARY!'],
  '3d-epic': ['EPIC', 'WIN!'],
  '3d-mythical': ['MYTHICAL!'],
  '3d-godlike': ['GODLIKE!'],
  '3d-transcendent': ['TRANSCENDENT!'],
  '3d-ouch': ['OUCH!'],
  '3d-bruised': ['BRUISED!'],
  '3d-wounded': ['WOUNDED!'],
  '3d-bleeding': ['BLEEDING!'],
  '3d-crushed': ['CRUSHED!'],
  '3d-shattered': ['SHATTERED!'],
  '3d-obliterated': ['OBLITERATED!'],
  '3d-annihilated': ['ANNIHILATED!'],
  '3d-vaporized': ['VAPORIZED!'],
  '3d-rug-burning': ['RUG', 'PULLED!'],
  '3d-fire': ['ON', 'FIRE!'],
  '3d-mega': ['MEGA', 'WIN!'],
  '3d-win': ['BIG', 'WIN!'],
}; 