
import type { LossTier, LossTierConfig } from '@/lib/types/celebrations';


export const LOSS_TIERS: Record<LossTier, LossTierConfig> = {
  small: {
    threshold: 1.0, 
    name: 'Small Loss',
    particles: {
      particleCount: 15,
      spread: 30,
      colors: ['#fca5a5', '#f87171'],
      direction: 'downward' as const,
      gravity: 0.8,
    },
    animation: {
      duration: 800,
      cardAnimation: 'gentleDim',
      screenEffect: 'none',
      effectIntensity: 'minimal',
    },
    audio: {
      melody: ['C4', 'G3'], 
      percussive: false,
      volume: 0.4,
    },
    borderEffect: {
      duration: 600,
      colors: ['#fca5a5'], 
      pattern: 'pulse',
      intensity: 'subtle',
    },
  },
  moderate: {
    threshold: 2.0, 
    name: 'Moderate Loss',
    particles: {
      particleCount: 30,
      spread: 45,
      colors: ['#f87171', '#ef4444'],
      direction: 'downward' as const,
      gravity: 1.0,
    },
    animation: {
      duration: 1200,
      cardAnimation: 'moderateDim',
      screenEffect: 'none',
      effectIntensity: 'light',
    },
    audio: {
      melody: ['C4', 'Am', 'F3'], 
      percussive: false,
      volume: 0.5,
    },
    borderEffect: {
      duration: 1000,
      colors: ['#f87171', '#ef4444'],
      pattern: 'beam',
      intensity: 'moderate',
    },
  },
  significant: {
    threshold: 3.0, 
    name: 'Significant Loss',
    particles: {
      particleCount: 50,
      spread: 60,
      colors: ['#ef4444', '#dc2626', '#b91c1c'],
      direction: 'downward' as const,
      gravity: 1.2,
      pattern: 'melting' as const,
    },
    animation: {
      duration: 1500,
      cardAnimation: 'notableDim',
      screenEffect: 'subtle-tint',
      effectIntensity: 'moderate',
    },
    audio: {
      melody: ['C4', 'F3', 'Bb2'], 
      bassTones: ['C2'],
      percussive: false,
      volume: 0.6,
    },
    borderEffect: {
      duration: 1200,
      colors: ['#ef4444', '#dc2626'],
      pattern: 'glow',
      intensity: 'notable',
    },
  },
  major: {
    threshold: 4.0, 
    name: 'Major Loss',
    particles: {
      particleCount: 75,
      spread: 80,
      colors: ['#dc2626', '#b91c1c', '#991b1b'],
      direction: 'downward' as const,
      gravity: 1.5,
      pattern: 'draining' as const,
    },
    animation: {
      duration: 2000,
      cardAnimation: 'strongDim',
      screenEffect: 'light-pulse',
      effectIntensity: 'strong',
    },
    audio: {
      melody: ['C4', 'Ab3', 'F3', 'Db3'], 
      bassTones: ['C2', 'F1'],
      percussive: true,
      volume: 0.7,
    },
    borderEffect: {
      duration: 1600,
      colors: ['#dc2626', '#b91c1c'],
      pattern: 'heavy-beam',
      intensity: 'strong',
    },
  },
  devastating: {
    threshold: 5.0, 
    name: 'Devastating Loss',
    particles: {
      particleCount: 100,
      spread: 100,
      colors: ['#b91c1c', '#991b1b', '#7f1d1d'],
      direction: 'storm' as const,
      gravity: 2.0,
      pattern: 'chaos' as const,
    },
    animation: {
      duration: 2500,
      cardAnimation: 'devastatingDim',
      screenEffect: 'shake-flash',
      effectIntensity: 'heavy',
    },
    audio: {
      melody: ['C4', 'Ab3', 'F3', 'Db3', 'Bb2'], 
      bassTones: ['C2', 'F1', 'Bb0'],
      percussive: true,
      dramatic: true,
      volume: 0.8,
    },
    borderEffect: {
      duration: 2000,
      colors: ['#b91c1c', '#991b1b', '#7f1d1d'],
      pattern: 'storm',
      intensity: 'devastating',
    },
  },
  catastrophic: {
    threshold: 10.0, 
    name: 'Catastrophic Loss',
    particles: {
      particleCount: 150,
      spread: 120,
      colors: ['#991b1b', '#7f1d1d', '#450a0a'],
      direction: 'storm' as const,
      gravity: 2.5,
      pattern: 'chaos' as const,
      drift: 'heavy',
      velocity: 'fast' as const,
      duration: 3500,
    },
    animation: {
      duration: 3500,
      cardAnimation: 'catastrophicDim',
      screenEffect: 'shake-flash',
      effectIntensity: 'heavy',
    },
    audio: {
      melody: ['C4', 'Ab3', 'F3', 'Db3', 'Bb2', 'G2'], 
      bassTones: ['C1', 'F1', 'Bb0', 'C0'],
      percussive: true,
      dramatic: true,
      volume: 0.85,
    },
    borderEffect: {
      duration: 2500,
      colors: ['#991b1b', '#7f1d1d', '#450a0a'],
      pattern: 'storm',
      intensity: 'devastating',
    },
  },
  nuclear: {
    threshold: 25.0, 
    name: 'Nuclear Loss',
    particles: {
      particleCount: 200,
      spread: 150,
      colors: ['#7f1d1d', '#450a0a', '#1c0000'],
      direction: 'storm' as const,
      gravity: 3.0,
      pattern: 'chaos' as const,
      drift: 'extreme',
      velocity: 'extreme' as const,
      duration: 5000,
    },
    animation: {
      duration: 5000,
      cardAnimation: 'nuclearDim',
      screenEffect: 'shake-flash',
      effectIntensity: 'heavy',
    },
    audio: {
      melody: ['C4', 'Ab3', 'F3', 'Db3', 'Bb2', 'G2', 'Eb2'], 
      bassTones: ['C0', 'F0', 'Bb-1', 'C-1'],
      percussive: true,
      dramatic: true,
      volume: 0.9,
    },
    borderEffect: {
      duration: 3500,
      colors: ['#7f1d1d', '#450a0a', '#1c0000'],
      pattern: 'storm',
      intensity: 'devastating',
    },
  },
  apocalyptic: {
    threshold: 50.0, 
    name: 'Apocalyptic Loss',
    particles: {
      particleCount: 300,
      spread: 180,
      colors: ['#450a0a', '#1c0000', '#000000'],
      direction: 'storm' as const,
      gravity: 3.5,
      pattern: 'chaos' as const,
      drift: 'extreme',
      velocity: 'extreme' as const,
      duration: 7000,
    },
    animation: {
      duration: 7000,
      cardAnimation: 'apocalypticDim',
      screenEffect: 'shake-flash',
      effectIntensity: 'heavy',
    },
    audio: {
      melody: ['C4', 'Ab3', 'F3', 'Db3', 'Bb2', 'G2', 'Eb2', 'C2'], 
      bassTones: ['C-1', 'F-1', 'Bb-2', 'C-2'],
      percussive: true,
      dramatic: true,
      volume: 0.95,
    },
    borderEffect: {
      duration: 5000,
      colors: ['#450a0a', '#1c0000', '#000000'],
      pattern: 'storm',
      intensity: 'devastating',
    },
  },
  extinction: {
    threshold: 75.0, 
    name: 'Extinction Loss',
    particles: {
      particleCount: 400,
      spread: 200,
      colors: ['#1c0000', '#000000', '#330000'],
      direction: 'storm' as const,
      gravity: 4.0,
      pattern: 'chaos' as const,
      drift: 'extreme',
      velocity: 'extreme' as const,
      duration: 8000,
    },
    animation: {
      duration: 8000,
      cardAnimation: 'extinctionDim',
      screenEffect: 'shake-flash',
      effectIntensity: 'heavy',
    },
    audio: {
      melody: ['C4', 'Ab3', 'F3', 'Db3', 'Bb2', 'G2', 'Eb2', 'C2', 'Ab1'], 
      bassTones: ['C-2', 'F-2', 'Bb-3', 'C-3'],
      percussive: true,
      dramatic: true,
      volume: 1.0,
    },
    borderEffect: {
      duration: 6000,
      colors: ['#1c0000', '#000000', '#330000'],
      pattern: 'storm',
      intensity: 'devastating',
    },
  },
  total_loss: {
    threshold: 100.0, 
    name: 'Total Loss',
    particles: {
      particleCount: 500,
      spread: 360,
      colors: ['#000000', '#1a1a1a', '#333333', '#666666'], 
      direction: 'storm' as const,
      gravity: 1.0, 
      pattern: 'chaos' as const,
      drift: 'extreme',
      velocity: 'normal' as const, 
      duration: 12000,
    },
    animation: {
      duration: 12000,
      cardAnimation: 'phoenixSequence', 
      screenEffect: 'shake-flash',
      effectIntensity: 'heavy',
    },
    audio: {
      melody: ['C2', 'Ab2', 'F2', 'Db2', 'Bb1', 'G1', 'Eb1', 'C1', 'Ab0', 'F0', 'G0', 'C1'], 
      bassTones: ['C-3', 'F-3', 'G-2', 'C-1'], 
      percussive: true,
      dramatic: true,
      volume: 0.8, 
    },
    borderEffect: {
      duration: 8000,
      colors: ['#000000', '#1a1a1a', '#333333', '#666666'], 
      pattern: 'storm',
      intensity: 'devastating',
    },
  },
};